HOST: http://www.rekola.cz/api/

--- ReKola API ---
---
API pro komunikaci mobilního klienta se serverem.

Společné věci pro každý request:

- X-Api-Key: token, který uživatel získal po přihlášení.
- Error 401, pokud přihlašovací token není platný (např. session timeout).
- Requesty značené **(admin)** vrací 403, pokud uživatel není admin.
- Requesty značené <u>(wip)</u> zatím neodpovídají implementaci.
---


