HOST: http://www.rekola.cz/api/

--- ReKola API ---
---
API pro komunikaci mobilního klienta se serverem. API je otevřené, ale rádi bychom vytvářeli aplikace společně; vždy jednu pro každou platformu (iOS / Android / Windows Phone / ...). Věříme, že společně se to lépe táhne. Pokud tvoje platforma není na https://github.com/RekolaCZ, napiš nám prosím na info@rekola.cz a domluvíme se.



Společné věci pro každý request:

- X-Api-Key: token, který uživatel získal po přihlášení.
- Error 401, pokud přihlašovací token není platný (např. session timeout).
- Requesty značené **(admin)** vrací 403, pokud uživatel není admin.
---
